language: android
sudo: false
jdk: openjdk7
android:
  components:
  - tools
  - build-tools-23.0.2
  - extra-android-support
  - extra-android-m2repository
  - android-23
script:
- ./gradlew assembledebug
deploy:
  provider: releases
  user: grzegorznittner
  password:
    secure: izeX4As4Ox1oRu/hHEzQcV0dpLvMsjuhnoNLeZv60dhQEenErR0taCPZ9vqK11n/ZTd3sbflOp8WlZMPJWCddyAspFpex3sSVk206BGgdhNMXuIx4Sm37dLnb7Vl6EmDufVAYwRv/FOSGl9hSHgEisPO4jraTHIUuhqTvxa/v6k=
  skip_cleanup: true
  file: app/build/outputs/apk/app-debug.apk
  on:
    repo: grzegorznittner/chanu
    tags: true
